services:  
  postgres:    
    image: 'postgres:latest'    
    environment:        
      - 'POSTGRES_DB=ESCOLA_DB'       
      - 'POSTGRES_USER=root'       
      - 'POSTGRES_PASSWORD=root'    
    ports:      
      - '5432:5432'
    